### ISSUE TITLE
undefined method `log_class_name=' for RTP::Logger:Class

### ISSUE THREAD

**Issue by ghost** [turboladen/rtp#10]
Ever since I version bumped to the latest version of rtp and rtsp, I'm getting:

```
undefined method `log_class_name=' for RTP::Logger:Class
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtp-0.1.5/lib/rtp/receiver.rb:5:in `require_relative'
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtp-0.1.5/lib/rtp/receiver.rb:5:in `<top (required)>'
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtsp-0.4.5/lib/rtsp/client.rb:4:in `require'
/home/deployer/asd/shared/bundle/ruby/2.1.0/gems/rtsp-0.4.5/lib/rtsp/client.rb:4:in `<top (required)>'
```

All I have to do to trigger this error is: 

``` ruby
require 'rtsp/client'
```

Any ideas?

**Comment by gipsh** [comment]
for me this did the trick,

gem uninstall log_switch
gem install log_switch -v 0.4.0

**Comment by dpruessner** [comment]
@gipsh Thank you!
